### ISSUE TITLE
Remove for-loop concept from transformation

### ISSUE THREAD

**Issue by sklam** [numba/numba-rvsdg#18]
https://github.com/numba/numba-rvsdg/blob/b28b554f6cca0a5d342b13b8b0081bab05d35601/numba_rvsdg/core/transformations.py#L99

To stay pure and faithful to the original paper, i'd suggest removing the `SyntheticForIter`. As mentioned in OOB discussion, the transformation should be able to operate base on a interface of:

```python
class OpIFace:
    def is_jump(self) -> bool: ...
    def get_jump_targets(self)  -> Tuple[Label]: ...
```

If the FOR_ITER bytecode is doing too much, i suggest preprocessing it into synthetic small operations before the rvsdg transform.

**Comment by esc** [comment]
The idea of detecting and handling a Python for-loop specifically and using the `SyntheticForIter` was generalized away with #20 -- @sklam would you consider this PR sufficient to close this issue?
