### ISSUE TITLE
Single block loops not placed into loop region

### ISSUE THREAD

**Issue by sklam** [numba/numba-rvsdg#45]
From `DEBUGGRAPH=1 pytest numba_rvsdg/tests/test_mock_asm.py::test_mock_scfg_fuzzer_case36` of #42 .

Single block loops are not restructured:

CFG:
![Screenshot 2023-04-18 at 2 12 39 PM](https://user-images.githubusercontent.com/1929845/232881171-6ad32ffd-abe6-46bd-beef-717f7f291a75.png)
After loop restructuring
![Screenshot 2023-04-18 at 2 13 31 PM](https://user-images.githubusercontent.com/1929845/232881329-c8585a09-5b9a-427d-81ac-e6933af74714.png)

**Comment by esc** [comment]
This happens when there is a backedge from header to itself.

This is the reproducer:

```
        original = """
        "0":
            jt: ["1"]
        "1":
            jt: ["1", "2"]
        "2":
            jt: ["1", "3"]
        "3":
            jt: []
        """
```

And this is the rendering of it:

<img width="291" alt="Screen Shot 2023-04-20 at 14 46 39" src="https://user-images.githubusercontent.com/41563/233378552-3174a656-d8ba-44c1-8049-3f7991692172.png">

This, on the other hand is the rendering of the failed transform, as you can see the backedge from header to header has simply not been processed.

<img width="571" alt="Screen Shot 2023-04-20 at 15 17 47" src="https://user-images.githubusercontent.com/41563/233378830-68abda51-d4c4-4203-af22-587684a43f8d.png">

**Comment by esc** [comment]
The following patch will fix this case:

```
diff --git i/numba_rvsdg/core/transformations.py w/numba_rvsdg/core/transformations.py
index b3d59811b6..e991de2ba2 100644
--- i/numba_rvsdg/core/transformations.py
+++ w/numba_rvsdg/core/transformations.py
@@ -143,7 +143,7 @@ def loop_restructure_helper(scfg: SCFG, loop: Set[Label]):
                     # matters in this case.
                     new_jt[new_jt.index(jt)] = synth_assign
                 # If the target is the loop_head
-                elif jt in headers and label not in doms[jt]:
+                elif jt in headers: #and label not in doms[jt]:
                     # Create the assignment and record it
                     synth_assign = SynthenticAssignment(str(scfg.clg.new_index()))
                     new_blocks.add(synth_assign)
```

And yield the following, correct, result:

<img width="591" alt="Screen Shot 2023-04-20 at 15 26 45" src="https://user-images.githubusercontent.com/41563/233383645-c1778a35-e05c-4d57-828f-9177964d8258.png">


However, this breaks the fig.3  test with:

```
    def replace_jump_targets(self, jump_targets: Tuple) -> "BasicBlock":
        fallthrough = len(jump_targets) == 1
        old_branch_value_table = self.branch_value_table
        new_branch_value_table = {}
        for target in self.jump_targets:
            if target not in jump_targets:
                # ASSUMPTION: only one jump_target is being updated
                diff = set(jump_targets).difference(self.jump_targets)
>               assert len(diff) == 1
E               AssertionError

numba_rvsdg/core/datastructures/basic_block.py:94: AssertionError
```
```

**Comment by esc** [comment]
> However, this breaks the fig.3 test with:
> 
> ```
>     def replace_jump_targets(self, jump_targets: Tuple) -> "BasicBlock":
>         fallthrough = len(jump_targets) == 1
>         old_branch_value_table = self.branch_value_table
>         new_branch_value_table = {}
>         for target in self.jump_targets:
>             if target not in jump_targets:
>                 # ASSUMPTION: only one jump_target is being updated
>                 diff = set(jump_targets).difference(self.jump_targets)
> >               assert len(diff) == 1
> E               AssertionError
> 
> numba_rvsdg/core/datastructures/basic_block.py:94: AssertionError
> ```

This is the same error as in: https://github.com/numba/numba-rvsdg/issues/48
